// flow-typed signature: 09bbfcb203b9ca9a94a05d6fc0302e63
// flow-typed version: <<STUB>>/babel-plugin-transform-rename-import_v^2.3.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-rename-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-rename-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-rename-import/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-rename-import/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-rename-import/lib/index'>;
}
