// flow-typed signature: 4f9813e3d3380c684c59c9dc9002919b
// flow-typed version: <<STUB>>/babel-plugin-syntax-export-extensions_v^6.13.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-syntax-export-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-syntax-export-extensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-syntax-export-extensions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-syntax-export-extensions/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-syntax-export-extensions/lib/index'>;
}
