// flow-typed signature: 42f8746556687274cadbd04c72a93458
// flow-typed version: <<STUB>>/karma-jasmine-ajax_v^0.1.13/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-jasmine-ajax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-jasmine-ajax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-jasmine-ajax/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-jasmine-ajax/main.js' {
  declare module.exports: $Exports<'karma-jasmine-ajax/main'>;
}
