// flow-typed signature: 30b24a32d9f467e3c6922202f7c5cd27
// flow-typed version: <<STUB>>/karma-junit-reporter_v^1.2.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-junit-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-junit-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-junit-reporter/index' {
  declare module.exports: $Exports<'karma-junit-reporter'>;
}
declare module 'karma-junit-reporter/index.js' {
  declare module.exports: $Exports<'karma-junit-reporter'>;
}
