// flow-typed signature: 6e741c60fe84f77421d45f1278bd3c07
// flow-typed version: <<STUB>>/re-reselect_v^0.5.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   're-reselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 're-reselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 're-reselect/dist/index' {
  declare module.exports: any;
}

declare module 're-reselect/es/index' {
  declare module.exports: any;
}

declare module 're-reselect/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 're-reselect/dist/index.js' {
  declare module.exports: $Exports<'re-reselect/dist/index'>;
}
declare module 're-reselect/es/index.js' {
  declare module.exports: $Exports<'re-reselect/es/index'>;
}
declare module 're-reselect/lib/index.js' {
  declare module.exports: $Exports<'re-reselect/lib/index'>;
}
