// flow-typed signature: c43a474d849fdde39d0612b804363f5f
// flow-typed version: <<STUB>>/@babel/plugin-proposal-class-properties_v^7.3.0/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-class-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-class-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-class-properties/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-class-properties/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-class-properties/lib/index'>;
}
